include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated_plugin_registrant.dart"
  errors:
    invalid_annotation_target: ignore
    unused_import: warning
    unused_local_variable: warning

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - avoid_print
    - prefer_is_empty
    - prefer_is_not_empty
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - avoid_empty_else
    - avoid_relative_lib_imports
    - empty_statements
    - hash_and_equals
    - unawaited_futures
    - prefer_single_quotes
    - sort_child_properties_last
