/*
 * Copyright 2026 ClearView Hub Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeFnHekGWHN-9WO4XtoA6t_l1a8EPO0LU',
    appId: '1:862371581041:web:baa34e54eedd9a32dc5fd0',
    messagingSenderId: '862371581041',
    projectId: 'eyeconnect-65sog',
    authDomain: 'eyeconnect-65sog.firebaseapp.com',
    storageBucket: 'eyeconnect-65sog.firebasestorage.app',
    measurementId: 'G-1FXR3D9TDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUyEiLX7u1B2B-biAx51lBJNnQDFXvhKw',
    appId: '1:862371581041:android:55024a782a6e565adc5fd0',
    messagingSenderId: '862371581041',
    projectId: 'eyeconnect-65sog',
    storageBucket: 'eyeconnect-65sog.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_0EWhFuRm3VFsj_g1VM72zY4NkpMikNU',
    appId: '1:862371581041:ios:2c8358f2d0c13138dc5fd0',
    messagingSenderId: '862371581041',
    projectId: 'eyeconnect-65sog',
    storageBucket: 'eyeconnect-65sog.firebasestorage.app',
    iosClientId: '862371581041-3pk0c3ihdvg534bn5iagmupc5u2kef2i.apps.googleusercontent.com',
    iosBundleId: 'com.jmrsai.clearviewhub.clearviewHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_0EWhFuRm3VFsj_g1VM72zY4NkpMikNU',
    appId: '1:862371581041:ios:2c8358f2d0c13138dc5fd0',
    messagingSenderId: '862371581041',
    projectId: 'eyeconnect-65sog',
    storageBucket: 'eyeconnect-65sog.firebasestorage.app',
    iosClientId: '862371581041-3pk0c3ihdvg534bn5iagmupc5u2kef2i.apps.googleusercontent.com',
    iosBundleId: 'com.jmrsai.clearviewhub.clearviewHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH_r4QeTPX8jB3ERaQuyz2Gpz_b4hsTI0',
    appId: '1:862371581041:web:20e033765d7c4043dc5fd0',
    messagingSenderId: '862371581041',
    projectId: 'eyeconnect-65sog',
    authDomain: 'eyeconnect-65sog.firebaseapp.com',
    storageBucket: 'eyeconnect-65sog.firebasestorage.app',
    measurementId: 'G-13Y5L9LGSF',
  );
}
