import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../../domain/repositories/community_repository.dart';
import '../../data/repositories/supabase_community_repository.dart';
import '../../domain/entities/community.dart';
import '../../domain/entities/community_post.dart';

final communityRepositoryProvider = Provider<CommunityRepository>((ref) {
  return SupabaseCommunityRepository(Supabase.instance.client);
});

final communitiesProvider = FutureProvider<List<Community>>((ref) async {
  return ref.watch(communityRepositoryProvider).getCommunities();
});

final communityPostsProvider = StateNotifierProvider.family<CommunityPostsNotifier, AsyncValue<List<CommunityPost>>, String>((ref, communityId) {
  return CommunityPostsNotifier(ref.watch(communityRepositoryProvider), communityId);
});

class CommunityPostsNotifier extends StateNotifier<AsyncValue<List<CommunityPost>>> {
  final CommunityRepository _repository;
  final String _communityId;
  int _offset = 0;
  final int _limit = 20;

  CommunityPostsNotifier(this._repository, this._communityId) : super(const AsyncValue.loading()) {
    fetchPosts();
  }

  Future<void> fetchPosts({bool refresh = false}) async {
    if (refresh) {
      _offset = 0;
      state = const AsyncValue.loading();
    }

    try {
      final posts = await _repository.getPosts(
        communityId: _communityId,
        offset: _offset,
        limit: _limit,
      );
      
      final currentPosts = state.value ?? [];
      state = AsyncValue.data(refresh ? posts : [...currentPosts, ...posts]);
      _offset += posts.length;
    } catch (e, st) {
      state = AsyncValue.error(e, st);
    }
  }

  Future<void> toggleUpvote(String postId) async {
    final currentPosts = state.value;
    if (currentPosts == null) return;

    try {
      // Optimistic Update
      state = AsyncValue.data(currentPosts.map((post) {
        if (post.id == postId) {
          final isUpvoted = !post.isUpvotedByMe;
          return post.copyWith(
            isUpvotedByMe: isUpvoted,
            upvotes: isUpvoted ? post.upvotes + 1 : post.upvotes - 1,
            isDownvotedByMe: false, // Reset downvote
          );
        }
        return post;
      }).toList());

      await _repository.reactToPost(postId, 'upvote');
    } catch (e) {
      // Rollback logic could be added here
    }
  }

  Future<void> createPost(String title, String content, {bool isAnonymous = false}) async {
    try {
      final newPost = CommunityPost(
        id: '', // Generated by server
        communityId: _communityId,
        title: title,
        content: content,
        isAnonymous: isAnonymous,
      );

      final result = await _repository.createPost(newPost);
      
      final currentPosts = state.value ?? [];
      state = AsyncValue.data([result, ...currentPosts]);
    } catch (e) {
      rethrow;
    }
  }
}
